//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternativa
    {
        public int CodQuestao { get; set; }
        public int CodOrdem { get; set; }
        public string Enunciado { get; set; }
        public string Comentario { get; set; }
        public bool FlagGabarito { get; set; }
    
        public virtual Questao Questao { get; set; }
    }
}
