//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalTemaQuestao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvalTemaQuestao()
        {
            this.AvalQuesPessoaResposta = new HashSet<AvalQuesPessoaResposta>();
        }
    
        public int CodTema { get; set; }
        public int CodDisciplina { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodQuestao { get; set; }
    
        public virtual AvaliacaoTema AvaliacaoTema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvalQuesPessoaResposta> AvalQuesPessoaResposta { get; set; }
        public virtual QuestaoTema QuestaoTema { get; set; }
    }
}
