//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalAcadReposicao
    {
        public int CodTipoAvaliacao { get; set; }
        public int NumIdentificador { get; set; }
        public int Semestre { get; set; }
        public int Ano { get; set; }
        public int CodProfessor { get; set; }
        public int CodJustificacao { get; set; }
        public int CodSala { get; set; }
        public Nullable<double> Valor { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Justificacao Justificacao { get; set; }
    }
}
