//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.AvalAcadReposicao = new HashSet<AvalAcadReposicao>();
            this.AvaliacaoTema = new HashSet<AvaliacaoTema>();
            this.AvalPessoaResultado = new HashSet<AvalPessoaResultado>();
        }
    
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<System.DateTime> DtAplicacao { get; set; }
        public Nullable<int> Duracao { get; set; }
        public bool FlagLiberada { get; set; }
    
        public virtual AvalAcademica AvalAcademica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvalAcadReposicao> AvalAcadReposicao { get; set; }
        public virtual AvalAuto AvalAuto { get; set; }
        public virtual AvalAvi AvalAvi { get; set; }
        public virtual AvalCertificacao AvalCertificacao { get; set; }
        public virtual TipoAvaliacao TipoAvaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoTema> AvaliacaoTema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvalPessoaResultado> AvalPessoaResultado { get; set; }
    }
}
