//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalQuesPessoaResposta
    {
        public int CodPessoaFisica { get; set; }
        public int CodTema { get; set; }
        public int CodDisciplina { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Semestre { get; set; }
        public int Ano { get; set; }
        public int CodQuestao { get; set; }
        public Nullable<int> RespAlternativa { get; set; }
        public string RespDiscursiva { get; set; }
        public string RespComentario { get; set; }
        public Nullable<double> RespNota { get; set; }
        public string ProfObservacao { get; set; }
    
        public virtual PessoaFisica PessoaFisica { get; set; }
        public virtual AvalTemaQuestao AvalTemaQuestao { get; set; }
    }
}
