//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalAuto
    {
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Semestre { get; set; }
        public int Ano { get; set; }
        public int CodDificuldade { get; set; }
        public int CodPessoaFisica { get; set; }
        public Nullable<bool> FlagArquivo { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Dificuldade Dificuldade { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
    }
}
