//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalPessoaResultado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvalPessoaResultado()
        {
            this.Justificacao = new HashSet<Justificacao>();
        }
    
        public int CodPessoaFisica { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Semestre { get; set; }
        public int Ano { get; set; }
        public Nullable<System.DateTime> HoraTermino { get; set; }
        public Nullable<int> QteAcertoObj { get; set; }
        public Nullable<double> Nota { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Justificacao> Justificacao { get; set; }
    }
}
