//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoTema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvaliacaoTema()
        {
            this.AvalTemaQuestao = new HashSet<AvalTemaQuestao>();
        }
    
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int NumIdentificador { get; set; }
        public int CodDisciplina { get; set; }
        public int CodTema { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Tema Tema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvalTemaQuestao> AvalTemaQuestao { get; set; }
    }
}
