//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoProrrogacao
    {
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int NumIdentificador { get; set; }
        public System.DateTime DtProrrogacao { get; set; }
        public Nullable<int> DuracaoAnterior { get; set; }
        public Nullable<int> DuracaoNova { get; set; }
        public string Observacao { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
    }
}
