//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AviPublico
    {
        public int CodOrdem { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodAviTipoPublico { get; set; }
    
        public virtual AvalAvi AvalAvi { get; set; }
        public virtual AviTipoPublico AviTipoPublico { get; set; }
        public virtual Campus Campus { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Diretoria Diretoria { get; set; }
        public virtual Instituicao Instituicao { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
        public virtual ProReitoria ProReitoria { get; set; }
        public virtual Reitoria Reitoria { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
