//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AviQuestao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AviQuestao()
        {
            this.AviQuestaoAlternativa = new HashSet<AviQuestaoAlternativa>();
            this.AviQuestaoPessoaResposta = new HashSet<AviQuestaoPessoaResposta>();
        }
    
        public int CodOrdem { get; set; }
        public int NumIdentificador { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodAviIndicador { get; set; }
        public int CodAviCategoria { get; set; }
        public int CodAviModulo { get; set; }
        public string Enunciado { get; set; }
        public string Observacao { get; set; }
        public Nullable<bool> FlagDiscursiva { get; set; }
    
        public virtual AvalAvi AvalAvi { get; set; }
        public virtual AviCategoria AviCategoria { get; set; }
        public virtual AviIndicador AviIndicador { get; set; }
        public virtual AviModulo AviModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AviQuestaoAlternativa> AviQuestaoAlternativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AviQuestaoPessoaResposta> AviQuestaoPessoaResposta { get; set; }
    }
}
