//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidato()
        {
            this.SimCandidato = new HashSet<SimCandidato>();
        }
    
        public int CodCandidato { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public Nullable<int> RgNumero { get; set; }
        public string RgOrgao { get; set; }
        public Nullable<System.DateTime> RgDtExpedicao { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public string Sexo { get; set; }
        public string Matricula { get; set; }
        public string TelefoneFixo { get; set; }
        public string TelefoneCelular { get; set; }
        public Nullable<int> CodPais { get; set; }
        public Nullable<int> CodEstado { get; set; }
        public Nullable<int> CodMunicipio { get; set; }
        public Nullable<bool> FlagAdventista { get; set; }
        public Nullable<bool> FlagNecessidadeEspecial { get; set; }
        public string DescricaoNecessidadeEspecial { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCandidato> SimCandidato { get; set; }
    }
}
