//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSIACEntities : DbContext
    {
        public dbSIACEntities()
            : base("name=dbSIACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alternativa> Alternativa { get; set; }
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AvalAcademica> AvalAcademica { get; set; }
        public virtual DbSet<AvalAcadReposicao> AvalAcadReposicao { get; set; }
        public virtual DbSet<AvalAuto> AvalAuto { get; set; }
        public virtual DbSet<AvalAvi> AvalAvi { get; set; }
        public virtual DbSet<AvalCertificacao> AvalCertificacao { get; set; }
        public virtual DbSet<Avaliacao> Avaliacao { get; set; }
        public virtual DbSet<AvaliacaoTema> AvaliacaoTema { get; set; }
        public virtual DbSet<AvalPessoaResultado> AvalPessoaResultado { get; set; }
        public virtual DbSet<AvalQuesPessoaResposta> AvalQuesPessoaResposta { get; set; }
        public virtual DbSet<AvalTemaQuestao> AvalTemaQuestao { get; set; }
        public virtual DbSet<AviCategoria> AviCategoria { get; set; }
        public virtual DbSet<AviIndicador> AviIndicador { get; set; }
        public virtual DbSet<AviModulo> AviModulo { get; set; }
        public virtual DbSet<AviPublico> AviPublico { get; set; }
        public virtual DbSet<AviQuestao> AviQuestao { get; set; }
        public virtual DbSet<AviQuestaoAlternativa> AviQuestaoAlternativa { get; set; }
        public virtual DbSet<AviQuestaoPessoaResposta> AviQuestaoPessoaResposta { get; set; }
        public virtual DbSet<AviTipoPublico> AviTipoPublico { get; set; }
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Campus> Campus { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<DiaSemana> DiaSemana { get; set; }
        public virtual DbSet<Dificuldade> Dificuldade { get; set; }
        public virtual DbSet<Diretoria> Diretoria { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Instituicao> Instituicao { get; set; }
        public virtual DbSet<Justificacao> Justificacao { get; set; }
        public virtual DbSet<MatrizCurricular> MatrizCurricular { get; set; }
        public virtual DbSet<MatrizCurricularDisciplina> MatrizCurricularDisciplina { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<NivelEnsino> NivelEnsino { get; set; }
        public virtual DbSet<Ocupacao> Ocupacao { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<PessoaFisica> PessoaFisica { get; set; }
        public virtual DbSet<PessoaFormacao> PessoaFormacao { get; set; }
        public virtual DbSet<PessoaJuridica> PessoaJuridica { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<ProReitoria> ProReitoria { get; set; }
        public virtual DbSet<Questao> Questao { get; set; }
        public virtual DbSet<QuestaoAnexo> QuestaoAnexo { get; set; }
        public virtual DbSet<QuestaoTema> QuestaoTema { get; set; }
        public virtual DbSet<Reitoria> Reitoria { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<TipoAnexo> TipoAnexo { get; set; }
        public virtual DbSet<TipoAvaliacao> TipoAvaliacao { get; set; }
        public virtual DbSet<TipoContato> TipoContato { get; set; }
        public virtual DbSet<TipoQuestao> TipoQuestao { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<TurmaDiscAluno> TurmaDiscAluno { get; set; }
        public virtual DbSet<TurmaDiscProfHorario> TurmaDiscProfHorario { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioAcesso> UsuarioAcesso { get; set; }
        public virtual DbSet<UsuarioAcessoPagina> UsuarioAcessoPagina { get; set; }
        public virtual DbSet<UsuarioOpiniao> UsuarioOpiniao { get; set; }
        public virtual DbSet<Visitante> Visitante { get; set; }
    }
}
