//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int CodOrdem { get; set; }
        public int CodPessoa { get; set; }
        public int CodMunicipio { get; set; }
        public int CodBairro { get; set; }
        public int CodPais { get; set; }
        public int CodEstado { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public Nullable<int> Cep { get; set; }
    
        public virtual Bairro Bairro { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
