//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Justificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Justificacao()
        {
            this.AvalAcadReposicao = new HashSet<AvalAcadReposicao>();
        }
    
        public int CodJustificacao { get; set; }
        public int CodProfessor { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int CodTipoAvaliacao { get; set; }
        public int NumIdentificador { get; set; }
        public int CodPessoaFisica { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<System.DateTime> DtConfirmacao { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvalAcadReposicao> AvalAcadReposicao { get; set; }
        public virtual AvalPessoaResultado AvalPessoaResultado { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
