//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizCurricularDisciplina
    {
        public int CodCurso { get; set; }
        public int CodMatriz { get; set; }
        public int CodDisciplina { get; set; }
        public int Periodo { get; set; }
        public int DiscCargaHoraria { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual MatrizCurricular MatrizCurricular { get; set; }
    }
}
