//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int CodParametro { get; set; }
        public int TempoInatividade { get; set; }
        public int NumeracaoQuestao { get; set; }
        public int NumeracaoAlternativa { get; set; }
        public int QteSemestres { get; set; }
        public int PeriodoLetivoAnoAtual { get; set; }
        public int PeriodoLetivoSemestreAtual { get; set; }
        public string TermoResponsabilidade { get; set; }
        public string NotaUsoAcademica { get; set; }
        public double ValorNotaMedia { get; set; }
        public string NotaUsoReposicao { get; set; }
        public string NotaUsoCertificacao { get; set; }
        public string NotaUsoInstitucional { get; set; }
        public string CoordenadorAVI { get; set; }
    }
}
