//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int Id { get; set; }
        public Nullable<int> TempoInatividade { get; set; }
        public Nullable<int> NumeracaoQuestao { get; set; }
        public Nullable<int> NumeracaoAlternativa { get; set; }
        public Nullable<int> QteSemestres { get; set; }
    }
}
