//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaFormacao
    {
        public int CodPessoaFisica { get; set; }
        public int CodArea { get; set; }
        public int CodNivelEnsino { get; set; }
        public int CodOrdem { get; set; }
        public string Curso { get; set; }
        public Nullable<int> Ano { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual NivelEnsino NivelEnsino { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
    }
}
