//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaLocalTrabalho
    {
        public int CodPessoa { get; set; }
        public int CodInstituicao { get; set; }
        public Nullable<int> CodReitoria { get; set; }
        public Nullable<int> CodProReitoria { get; set; }
        public Nullable<int> CodCampus { get; set; }
        public Nullable<int> CodDiretoria { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Diretoria Diretoria { get; set; }
        public virtual Instituicao Instituicao { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
        public virtual Reitoria Reitoria { get; set; }
        public virtual ProReitoria ProReitoria { get; set; }
    }
}
