//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoAnexo
    {
        public int CodOrdem { get; set; }
        public int CodTipoAnexo { get; set; }
        public int CodQuestao { get; set; }
        public byte[] Anexo { get; set; }
        public string Legenda { get; set; }
        public string Fonte { get; set; }
    
        public virtual Questao Questao { get; set; }
        public virtual TipoAnexo TipoAnexo { get; set; }
    }
}
