//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questao()
        {
            this.Alternativa = new HashSet<Alternativa>();
            this.QuestaoAnexo = new HashSet<QuestaoAnexo>();
            this.QuestaoTema = new HashSet<QuestaoTema>();
        }
    
        public int CodQuestao { get; set; }
        public int CodProfessor { get; set; }
        public int CodDificuldade { get; set; }
        public int CodTipoQuestao { get; set; }
        public string Enunciado { get; set; }
        public string Objetivo { get; set; }
        public string Comentario { get; set; }
        public string ChaveDeResposta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alternativa> Alternativa { get; set; }
        public virtual Dificuldade Dificuldade { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual TipoQuestao TipoQuestao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestaoAnexo> QuestaoAnexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestaoTema> QuestaoTema { get; set; }
    }
}
