//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCandidatoQuestao
    {
        public int Ano { get; set; }
        public int NumIdentificador { get; set; }
        public int CodCandidato { get; set; }
        public int CodDiaRealizacao { get; set; }
        public int CodProva { get; set; }
        public int CodQuestao { get; set; }
        public Nullable<int> RespAlternativa { get; set; }
        public string RespDiscursiva { get; set; }
        public Nullable<decimal> NotaDiscursiva { get; set; }
    
        public virtual SimCandidatoProva SimCandidatoProva { get; set; }
        public virtual SimProvaQuestao SimProvaQuestao { get; set; }
    }
}
