//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCandidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimCandidato()
        {
            this.SimCandidatoProva = new HashSet<SimCandidatoProva>();
        }
    
        public int Ano { get; set; }
        public int NumIdentificador { get; set; }
        public int CodCandidato { get; set; }
        public int NumInscricao { get; set; }
        public System.DateTime DtInscricao { get; set; }
        public int CodSala { get; set; }
        public Nullable<decimal> EscorePadronizadoFinal { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual Simulado Simulado { get; set; }
        public virtual SimSala SimSala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCandidatoProva> SimCandidatoProva { get; set; }
    }
}
