//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimDiaRealizacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimDiaRealizacao()
        {
            this.SimProva = new HashSet<SimProva>();
        }
    
        public int Ano { get; set; }
        public int NumIdentificador { get; set; }
        public int CodDiaRealizacao { get; set; }
        public System.DateTime DtRealizacao { get; set; }
        public string CodTurno { get; set; }
        public int Duracao { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual Simulado Simulado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimProva> SimProva { get; set; }
    }
}
