//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimProvaQuestao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimProvaQuestao()
        {
            this.SimCandidatoQuestao = new HashSet<SimCandidatoQuestao>();
        }
    
        public int Ano { get; set; }
        public int NumIdentificador { get; set; }
        public int CodDiaRealizacao { get; set; }
        public int CodProva { get; set; }
        public int CodQuestao { get; set; }
    
        public virtual Questao Questao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCandidatoQuestao> SimCandidatoQuestao { get; set; }
        public virtual SimProva SimProva { get; set; }
    }
}
