//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simulado()
        {
            this.SimCandidato = new HashSet<SimCandidato>();
            this.SimDiaRealizacao = new HashSet<SimDiaRealizacao>();
            this.SimSala = new HashSet<SimSala>();
        }
    
        public int Ano { get; set; }
        public int NumIdentificador { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int CodColaborador { get; set; }
        public System.DateTime DtInicioInscricao { get; set; }
        public System.DateTime DtTerminoInscricao { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<int> QteVagas { get; set; }
        public bool FlagSimuladoEncerrado { get; set; }
        public bool FlagInscricaoEncerrado { get; set; }
        public bool FlagProvaEncerrada { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCandidato> SimCandidato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimDiaRealizacao> SimDiaRealizacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimSala> SimSala { get; set; }
    }
}
