//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int CodOrdem { get; set; }
        public int CodPessoa { get; set; }
        public int CodTipoContato { get; set; }
        public Nullable<int> CodDDI { get; set; }
        public Nullable<int> CodDDD { get; set; }
        public string Numero { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual TipoContato TipoContato { get; set; }
    }
}
