//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaDiscProfHorario
    {
        public int AnoLetivo { get; set; }
        public int SemestreLetivo { get; set; }
        public int CodDisciplina { get; set; }
        public int CodProfessor { get; set; }
        public int CodDia { get; set; }
        public string CodTurno { get; set; }
        public int CodHorario { get; set; }
        public int CodGrupo { get; set; }
        public int CodCurso { get; set; }
        public int Periodo { get; set; }
        public int NumTurma { get; set; }
        public int CodSala { get; set; }
    
        public virtual DiaSemana DiaSemana { get; set; }
        public virtual Disciplina Disciplina { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
