//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioOpiniao
    {
        public int CodOrdem { get; set; }
        public string Matricula { get; set; }
        public string Opiniao { get; set; }
        public Nullable<System.DateTime> DtEnvio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
