//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAcessoPagina
    {
        public int NumIdentificador { get; set; }
        public string Matricula { get; set; }
        public int CodOrdem { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> DtAbertura { get; set; }
        public string PaginaReferencia { get; set; }
    
        public virtual UsuarioAcesso UsuarioAcesso { get; set; }
    }
}
