//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitante
    {
        public int CodVisitante { get; set; }
        public string MatrVisitante { get; set; }
        public Nullable<System.DateTime> DtValidade { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
