namespace SIAC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SetUnicode : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Aluno", "MatrAluno", "dbo.Usuario");
            DropForeignKey("dbo.Candidato", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.Colaborador", "MatrColaborador", "dbo.Usuario");
            DropForeignKey("dbo.Professor", "MatrProfessor", "dbo.Usuario");
            DropForeignKey("dbo.UsuarioAcesso", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.UsuarioOpiniao", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.Visitante", "MatrVisitante", "dbo.Usuario");
            DropForeignKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" }, "dbo.UsuarioAcesso");
            DropIndex("dbo.Colaborador", new[] { "MatrColaborador" });
            DropIndex("dbo.Aluno", new[] { "MatrAluno" });
            DropIndex("dbo.Professor", new[] { "MatrProfessor" });
            DropIndex("dbo.Candidato", new[] { "Matricula" });
            DropIndex("dbo.UsuarioAcesso", new[] { "Matricula" });
            DropIndex("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" });
            DropIndex("dbo.UsuarioOpiniao", new[] { "Matricula" });
            DropIndex("dbo.Visitante", new[] { "MatrVisitante" });
            DropPrimaryKey("dbo.Usuario");
            DropPrimaryKey("dbo.UsuarioAcesso");
            DropPrimaryKey("dbo.UsuarioAcessoPagina");
            DropPrimaryKey("dbo.UsuarioOpiniao");
            AlterColumn("dbo.Alternativa", "Enunciado", c => c.String(nullable: false, maxLength: 250));
            AlterColumn("dbo.Alternativa", "Comentario", c => c.String(maxLength: 250));
            AlterColumn("dbo.Questao", "Enunciado", c => c.String(nullable: false, maxLength: 250));
            AlterColumn("dbo.Questao", "Objetivo", c => c.String(maxLength: 250));
            AlterColumn("dbo.Questao", "Comentario", c => c.String(maxLength: 250));
            AlterColumn("dbo.Dificuldade", "Descricao", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Dificuldade", "Comentario", c => c.String(maxLength: 255));
            AlterColumn("dbo.Disciplina", "Descricao", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Disciplina", "Sigla", c => c.String(maxLength: 10));
            AlterColumn("dbo.PessoaFisica", "Nome", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Sala", "Descricao", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Sala", "Sigla", c => c.String(maxLength: 15));
            AlterColumn("dbo.Sala", "RefLocal", c => c.String(maxLength: 255));
            AlterColumn("dbo.Sala", "Observacao", c => c.String(maxLength: 140));
            AlterColumn("dbo.Bloco", "Descricao", c => c.String(maxLength: 100));
            AlterColumn("dbo.Bloco", "Sigla", c => c.String(maxLength: 15));
            AlterColumn("dbo.Bloco", "RefLocal", c => c.String(maxLength: 255));
            AlterColumn("dbo.Bloco", "Observacao", c => c.String(maxLength: 140));
            AlterColumn("dbo.Campus", "Sigla", c => c.String(maxLength: 10));
            AlterColumn("dbo.AvalAvi", "Titulo", c => c.String(nullable: false, maxLength: 250));
            AlterColumn("dbo.AviQuestao", "Enunciado", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.AviQuestao", "Observacao", c => c.String(maxLength: 255));
            AlterColumn("dbo.AviCategoria", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AviCategoria", "Observacao", c => c.String(maxLength: 255));
            AlterColumn("dbo.AviIndicador", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AviIndicador", "Observacao", c => c.String(maxLength: 255));
            AlterColumn("dbo.AviModulo", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AviModulo", "Observacao", c => c.String(maxLength: 255));
            AlterColumn("dbo.AviQuestaoAlternativa", "Enunciado", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Colaborador", "MatrColaborador", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Curso", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Curso", "Sigla", c => c.String(maxLength: 30));
            AlterColumn("dbo.Aluno", "MatrAluno", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Turma", "Nome", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.DiaSemana", "Descricao", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.Turno", "Descricao", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.SimProva", "Titulo", c => c.String(maxLength: 200));
            AlterColumn("dbo.SimProva", "Descricao", c => c.String(maxLength: 500));
            AlterColumn("dbo.Professor", "MatrProfessor", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Usuario", "Matricula", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Candidato", "Nome", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Candidato", "Cpf", c => c.String(nullable: false, maxLength: 11, fixedLength: true));
            AlterColumn("dbo.Candidato", "RgOrgao", c => c.String(maxLength: 20));
            AlterColumn("dbo.Candidato", "Email", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Candidato", "Senha", c => c.String(nullable: false, maxLength: 64, fixedLength: true));
            AlterColumn("dbo.Candidato", "Sexo", c => c.String(maxLength: 1, fixedLength: true));
            AlterColumn("dbo.Candidato", "Matricula", c => c.String(maxLength: 20));
            AlterColumn("dbo.Candidato", "TelefoneFixo", c => c.String(maxLength: 20));
            AlterColumn("dbo.Candidato", "TelefoneCelular", c => c.String(maxLength: 20));
            AlterColumn("dbo.Candidato", "DescricaoNecessidadeEspecial", c => c.String(maxLength: 255));
            AlterColumn("dbo.Municipio", "Descricao", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Bairro", "Descricao", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Endereco", "Logradouro", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Endereco", "Numero", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Endereco", "Complemento", c => c.String(maxLength: 140));
            AlterColumn("dbo.Email", "Email", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.TipoContato", "Descricao", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Telefone", "Numero", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.PessoaJuridica", "RazaoSocial", c => c.String(maxLength: 255));
            AlterColumn("dbo.PessoaJuridica", "NomeFantasia", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.PessoaJuridica", "Portal", c => c.String(maxLength: 100));
            AlterColumn("dbo.Diretoria", "Sigla", c => c.String(maxLength: 10));
            AlterColumn("dbo.Instituicao", "Sigla", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.ProReitoria", "Sigla", c => c.String(maxLength: 10));
            AlterColumn("dbo.Reitoria", "Sigla", c => c.String(maxLength: 10));
            AlterColumn("dbo.Estado", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Estado", "Sigla", c => c.String(maxLength: 2));
            AlterColumn("dbo.Pais", "Descricao", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Pais", "Sigla", c => c.String(maxLength: 5));
            AlterColumn("dbo.SimCandidato", "NumeroMascara", c => c.String(maxLength: 50));
            AlterColumn("dbo.Simulado", "Titulo", c => c.String(nullable: false, maxLength: 250));
            AlterColumn("dbo.Categoria", "Descricao", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.UsuarioAcesso", "Matricula", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.UsuarioAcesso", "IpAcesso", c => c.String(maxLength: 50));
            AlterColumn("dbo.UsuarioAcessoPagina", "Matricula", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.UsuarioAcessoPagina", "Pagina", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.UsuarioAcessoPagina", "PaginaReferencia", c => c.String(maxLength: 200));
            AlterColumn("dbo.UsuarioOpiniao", "Matricula", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Visitante", "MatrVisitante", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.NivelEnsino", "Descricao", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.NivelEnsino", "Sigla", c => c.String(maxLength: 5));
            AlterColumn("dbo.PessoaFormacao", "Curso", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Area", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AviTipoPublico", "Descricao", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.AvalQuesPessoaResposta", "RespComentario", c => c.String(maxLength: 250));
            AlterColumn("dbo.AvalQuesPessoaResposta", "ProfObservacao", c => c.String(maxLength: 250));
            AlterColumn("dbo.Tema", "Descricao", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Tema", "Comentario", c => c.String(maxLength: 250));
            AlterColumn("dbo.Ocupacao", "Descricao", c => c.String(maxLength: 40));
            AlterColumn("dbo.AvaliacaoProrrogacao", "Observacao", c => c.String(maxLength: 255));
            AlterColumn("dbo.TipoAvaliacao", "Descricao", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.TipoAvaliacao", "Sigla", c => c.String(maxLength: 4));
            AlterColumn("dbo.QuestaoAnexo", "Legenda", c => c.String(maxLength: 250));
            AlterColumn("dbo.QuestaoAnexo", "Fonte", c => c.String(maxLength: 250));
            AlterColumn("dbo.TipoAnexo", "Descricao", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.TipoQuestao", "Descricao", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.TipoQuestao", "Sigla", c => c.String(maxLength: 4));
            AlterColumn("dbo.Parametro", "SmtpEnderecoHost", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Parametro", "SmtpUsuario", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Parametro", "SmtpSenha", c => c.String(nullable: false, maxLength: 200));
            AddPrimaryKey("dbo.Usuario", "Matricula");
            AddPrimaryKey("dbo.UsuarioAcesso", new[] { "Matricula", "CodOrdem" });
            AddPrimaryKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem", "NumIdentificador" });
            AddPrimaryKey("dbo.UsuarioOpiniao", new[] { "Matricula", "CodOrdem" });
            CreateIndex("dbo.Colaborador", "MatrColaborador");
            CreateIndex("dbo.Aluno", "MatrAluno");
            CreateIndex("dbo.Professor", "MatrProfessor");
            CreateIndex("dbo.Candidato", "Matricula");
            CreateIndex("dbo.UsuarioAcesso", "Matricula");
            CreateIndex("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" });
            CreateIndex("dbo.UsuarioOpiniao", "Matricula");
            CreateIndex("dbo.Visitante", "MatrVisitante");
            AddForeignKey("dbo.Aluno", "MatrAluno", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Candidato", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Colaborador", "MatrColaborador", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Professor", "MatrProfessor", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.UsuarioAcesso", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.UsuarioOpiniao", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Visitante", "MatrVisitante", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" }, "dbo.UsuarioAcesso", new[] { "Matricula", "CodOrdem" });
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" }, "dbo.UsuarioAcesso");
            DropForeignKey("dbo.Visitante", "MatrVisitante", "dbo.Usuario");
            DropForeignKey("dbo.UsuarioOpiniao", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.UsuarioAcesso", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.Professor", "MatrProfessor", "dbo.Usuario");
            DropForeignKey("dbo.Colaborador", "MatrColaborador", "dbo.Usuario");
            DropForeignKey("dbo.Candidato", "Matricula", "dbo.Usuario");
            DropForeignKey("dbo.Aluno", "MatrAluno", "dbo.Usuario");
            DropIndex("dbo.Visitante", new[] { "MatrVisitante" });
            DropIndex("dbo.UsuarioOpiniao", new[] { "Matricula" });
            DropIndex("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" });
            DropIndex("dbo.UsuarioAcesso", new[] { "Matricula" });
            DropIndex("dbo.Candidato", new[] { "Matricula" });
            DropIndex("dbo.Professor", new[] { "MatrProfessor" });
            DropIndex("dbo.Aluno", new[] { "MatrAluno" });
            DropIndex("dbo.Colaborador", new[] { "MatrColaborador" });
            DropPrimaryKey("dbo.UsuarioOpiniao");
            DropPrimaryKey("dbo.UsuarioAcessoPagina");
            DropPrimaryKey("dbo.UsuarioAcesso");
            DropPrimaryKey("dbo.Usuario");
            AlterColumn("dbo.Parametro", "SmtpSenha", c => c.String(nullable: false, maxLength: 200, unicode: false));
            AlterColumn("dbo.Parametro", "SmtpUsuario", c => c.String(nullable: false, maxLength: 200, unicode: false));
            AlterColumn("dbo.Parametro", "SmtpEnderecoHost", c => c.String(nullable: false, maxLength: 200, unicode: false));
            AlterColumn("dbo.TipoQuestao", "Sigla", c => c.String(maxLength: 4, unicode: false));
            AlterColumn("dbo.TipoQuestao", "Descricao", c => c.String(nullable: false, maxLength: 15, unicode: false));
            AlterColumn("dbo.TipoAnexo", "Descricao", c => c.String(nullable: false, maxLength: 30, unicode: false));
            AlterColumn("dbo.QuestaoAnexo", "Fonte", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.QuestaoAnexo", "Legenda", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.TipoAvaliacao", "Sigla", c => c.String(maxLength: 4, unicode: false));
            AlterColumn("dbo.TipoAvaliacao", "Descricao", c => c.String(nullable: false, maxLength: 30, unicode: false));
            AlterColumn("dbo.AvaliacaoProrrogacao", "Observacao", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Ocupacao", "Descricao", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.Tema", "Comentario", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Tema", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.AvalQuesPessoaResposta", "ProfObservacao", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.AvalQuesPessoaResposta", "RespComentario", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.AviTipoPublico", "Descricao", c => c.String(nullable: false, maxLength: 35, unicode: false));
            AlterColumn("dbo.Area", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.PessoaFormacao", "Curso", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.NivelEnsino", "Sigla", c => c.String(maxLength: 5, unicode: false));
            AlterColumn("dbo.NivelEnsino", "Descricao", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.Visitante", "MatrVisitante", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.UsuarioOpiniao", "Matricula", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.UsuarioAcessoPagina", "PaginaReferencia", c => c.String(maxLength: 200, unicode: false));
            AlterColumn("dbo.UsuarioAcessoPagina", "Pagina", c => c.String(nullable: false, maxLength: 200, unicode: false));
            AlterColumn("dbo.UsuarioAcessoPagina", "Matricula", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.UsuarioAcesso", "IpAcesso", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.UsuarioAcesso", "Matricula", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Categoria", "Descricao", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.Simulado", "Titulo", c => c.String(nullable: false, maxLength: 250, unicode: false));
            AlterColumn("dbo.SimCandidato", "NumeroMascara", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Pais", "Sigla", c => c.String(maxLength: 5, unicode: false));
            AlterColumn("dbo.Pais", "Descricao", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.Estado", "Sigla", c => c.String(maxLength: 2, unicode: false));
            AlterColumn("dbo.Estado", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Reitoria", "Sigla", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.ProReitoria", "Sigla", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.Instituicao", "Sigla", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Diretoria", "Sigla", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.PessoaJuridica", "Portal", c => c.String(maxLength: 100, unicode: false));
            AlterColumn("dbo.PessoaJuridica", "NomeFantasia", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.PessoaJuridica", "RazaoSocial", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Telefone", "Numero", c => c.String(nullable: false, maxLength: 15, unicode: false));
            AlterColumn("dbo.TipoContato", "Descricao", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Email", "Email", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Endereco", "Complemento", c => c.String(maxLength: 140, unicode: false));
            AlterColumn("dbo.Endereco", "Numero", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Endereco", "Logradouro", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Bairro", "Descricao", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.Municipio", "Descricao", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.Candidato", "DescricaoNecessidadeEspecial", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Candidato", "TelefoneCelular", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Candidato", "TelefoneFixo", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Candidato", "Matricula", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Candidato", "Sexo", c => c.String(maxLength: 1, fixedLength: true, unicode: false));
            AlterColumn("dbo.Candidato", "Senha", c => c.String(nullable: false, maxLength: 64, fixedLength: true, unicode: false));
            AlterColumn("dbo.Candidato", "Email", c => c.String(nullable: false, maxLength: 200, unicode: false));
            AlterColumn("dbo.Candidato", "RgOrgao", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Candidato", "Cpf", c => c.String(nullable: false, maxLength: 11, fixedLength: true, unicode: false));
            AlterColumn("dbo.Candidato", "Nome", c => c.String(nullable: false, maxLength: 255, unicode: false));
            AlterColumn("dbo.Usuario", "Matricula", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Professor", "MatrProfessor", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.SimProva", "Descricao", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.SimProva", "Titulo", c => c.String(maxLength: 200, unicode: false));
            AlterColumn("dbo.Turno", "Descricao", c => c.String(nullable: false, maxLength: 15, unicode: false));
            AlterColumn("dbo.DiaSemana", "Descricao", c => c.String(nullable: false, maxLength: 15, unicode: false));
            AlterColumn("dbo.Turma", "Nome", c => c.String(nullable: false, maxLength: 30, unicode: false));
            AlterColumn("dbo.Aluno", "MatrAluno", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Curso", "Sigla", c => c.String(maxLength: 30, unicode: false));
            AlterColumn("dbo.Curso", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Colaborador", "MatrColaborador", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.AviQuestaoAlternativa", "Enunciado", c => c.String(nullable: false, maxLength: 255, unicode: false));
            AlterColumn("dbo.AviModulo", "Observacao", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.AviModulo", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.AviIndicador", "Observacao", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.AviIndicador", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.AviCategoria", "Observacao", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.AviCategoria", "Descricao", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.AviQuestao", "Observacao", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.AviQuestao", "Enunciado", c => c.String(nullable: false, maxLength: 255, unicode: false));
            AlterColumn("dbo.AvalAvi", "Titulo", c => c.String(nullable: false, maxLength: 250, unicode: false));
            AlterColumn("dbo.Campus", "Sigla", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.Bloco", "Observacao", c => c.String(maxLength: 140, unicode: false));
            AlterColumn("dbo.Bloco", "RefLocal", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Bloco", "Sigla", c => c.String(maxLength: 15, unicode: false));
            AlterColumn("dbo.Bloco", "Descricao", c => c.String(maxLength: 100, unicode: false));
            AlterColumn("dbo.Sala", "Observacao", c => c.String(maxLength: 140, unicode: false));
            AlterColumn("dbo.Sala", "RefLocal", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Sala", "Sigla", c => c.String(maxLength: 15, unicode: false));
            AlterColumn("dbo.Sala", "Descricao", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.PessoaFisica", "Nome", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Disciplina", "Sigla", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.Disciplina", "Descricao", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.Dificuldade", "Comentario", c => c.String(maxLength: 255, unicode: false));
            AlterColumn("dbo.Dificuldade", "Descricao", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Questao", "Comentario", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Questao", "Objetivo", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Questao", "Enunciado", c => c.String(nullable: false, maxLength: 250, unicode: false));
            AlterColumn("dbo.Alternativa", "Comentario", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Alternativa", "Enunciado", c => c.String(nullable: false, maxLength: 250, unicode: false));
            AddPrimaryKey("dbo.UsuarioOpiniao", new[] { "Matricula", "CodOrdem" });
            AddPrimaryKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem", "NumIdentificador" });
            AddPrimaryKey("dbo.UsuarioAcesso", new[] { "Matricula", "CodOrdem" });
            AddPrimaryKey("dbo.Usuario", "Matricula");
            CreateIndex("dbo.Visitante", "MatrVisitante");
            CreateIndex("dbo.UsuarioOpiniao", "Matricula");
            CreateIndex("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" });
            CreateIndex("dbo.UsuarioAcesso", "Matricula");
            CreateIndex("dbo.Candidato", "Matricula");
            CreateIndex("dbo.Professor", "MatrProfessor");
            CreateIndex("dbo.Aluno", "MatrAluno");
            CreateIndex("dbo.Colaborador", "MatrColaborador");
            AddForeignKey("dbo.UsuarioAcessoPagina", new[] { "Matricula", "CodOrdem" }, "dbo.UsuarioAcesso", new[] { "Matricula", "CodOrdem" });
            AddForeignKey("dbo.Visitante", "MatrVisitante", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.UsuarioOpiniao", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.UsuarioAcesso", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Professor", "MatrProfessor", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Colaborador", "MatrColaborador", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Candidato", "Matricula", "dbo.Usuario", "Matricula");
            AddForeignKey("dbo.Aluno", "MatrAluno", "dbo.Usuario", "Matricula");
        }
    }
}
